[package]
name = "popo"
version = "0.1.0"
authors = ["Quentin Guilloteau <Quentin.Guilloteau@grenoble-inp.org>"]
edition = "2018"

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }
subprocess = "*"
time = "*"
clap = "*"
